/**
* This file is automatically generated by the command, npm run env:local|stage|prod
*
* Changes to this file are not tracked by git.
* To track changes, run:
*    git update-index --no-skip-worktree ./src/config/Config.ts
* 
* Helpful Link: https://stackoverflow.com/a/39776107/3543339
*/

import Config from '../types/Config.d';

const config = {
  'stage': true,
  'local': false,
  'prod': false
} as Config;

export default config;
