FROM node:18-alpine as builder
WORKDIR /app

RUN apk update && apk upgrade && apk add --no-cache python3 g++ make
RUN apk --no-cache --virtual build-dependencies add python3 g++ make

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
ARG PROD_ENVIRONMENT_FILE
RUN npm run env:prod
RUN npm run build



FROM nginx:1.23.1-alpine as deployment

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]